docker-build-master:
  # Official docker image.
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker buildx build --platform linux/arm/v7 --pull -t "$CI_REGISTRY_IMAGE:armv7" -f Dockerfile.armv7 .
    - docker push "$CI_REGISTRY_IMAGE:armv7"
    - docker buildx build --platform linux/arm64/v8 --pull -t "$CI_REGISTRY_IMAGE:arm64" -f Dockerfile.arm64 .
    - docker push "$CI_REGISTRY_IMAGE:arm64"
    - docker manifest create $CI_REGISTRY_IMAGE:latest $CI_REGISTRY_IMAGE:arm64 $CI_REGISTRY_IMAGE:armv7
    - docker manifest push $CI_REGISTRY_PASSWORD:latest

  only:
    - master
