FROM golang:alpine

ADD . /usr/src/bladerf-device-plugin

ENV GOOS=linux
ENV GOARCH=arm
ENV GOPATH=/usr/src
WORKDIR /usr/src/bladerf-device-plugin
RUN go mod tidy && go build -o bladerf-device-plugin

FROM --platform=linux/arm/v7 alpine 

COPY --from=0 /usr/src/bladerf-device-plugin/bladerf-device-plugin ./

ENTRYPOINT ["./bladerf-device-plugin"]
